const types = {
    FETCH_RACE_LIST_REQUEST: '@@races/FETCH_RACE_LIST_REQUEST',
    FETCH_RACE_LIST_SUCCESS: '@@races/FETCH_RACE_LIST_SUCCESS',
    FETCH_RACE_LIST_ERROR: '@@races/FETCH_RACE_LIST_ERROR',

    CREATE_RACE_REQUEST: '@@races/CREATE_RACE_REQUEST',
    CREATE_RACE_SUCCESS: '@@races/CREATE_RACE_SUCCESS',
    CREATE_RACE_ERROR: '@@races/CREATE_RACE_ERROR',

    SET_CURRENT_RACE_BY_ID: '@@races/SET_CURRENT_RACE_BY_ID',
    SET_CURRENT_RACE_AS_OBJECT: '@@races/SET_CURRENT_RACE_AS_OBJECT',

    NEW_ROOM_CREATED: '@@races/NEW_ROOM_CREATED',
    ROOM_CHANGED: '@@races/ROOM_CHANGED',
    ROOM_DELETED: '@@races/ROOM_DELETED',
};

export default types;
